import { TRANSACTION_CATEGORIES_ICONS } from "../../transaction/transaction-constants"

export const TRANSACTION_CATEGORIES_ICONS_LIST = [
  TRANSACTION_CATEGORIES_ICONS.APPLE,
  TRANSACTION_CATEGORIES_ICONS.BILLS,
  TRANSACTION_CATEGORIES_ICONS.CARROT,
  TRANSACTION_CATEGORIES_ICONS.COOKING_POT,
  TRANSACTION_CATEGORIES_ICONS.HAND_PLATER,
  TRANSACTION_CATEGORIES_ICONS.BIKE,
  TRANSACTION_CATEGORIES_ICONS.BUS,
  TRANSACTION_CATEGORIES_ICONS.CAR,
  TRANSACTION_CATEGORIES_ICONS.TRAIN,
  TRANSACTION_CATEGORIES_ICONS.FUEL,
  TRANSACTION_CATEGORIES_ICONS.FILM,
  TRANSACTION_CATEGORIES_ICONS.RSS,
  TRANSACTION_CATEGORIES_ICONS.CIGARETTE,
  TRANSACTION_CATEGORIES_ICONS.SMARTPHONE,
  TRANSACTION_CATEGORIES_ICONS.TRAM_FRONT,
  TRANSACTION_CATEGORIES_ICONS.USER,
] as const
