export const TRANSACTION_CATEGORIES_ICONS = {
  APPLE: "apple",
  BILLS: "bills",
  CARROT: "carrot",
  COOKING_POT: "cooking_pot",
  HAND_PLATER: "hand_plater",
  BIKE: "bike",
  BUS: "bus",
  CAR: "car",
  TRAIN: "train_front",
  FUEL: "fuel",
  FILM: "film",
  RSS: "rss",
  CIGARETTE: "cigarette",
  SMARTPHONE: "smartphone",
  TRAM_FRONT: "tram_front",
  USER: "user",
} as const
