export const TRANSACTIONS_FILTERS_SORT_DIRECTIONS = {
  DESC: "DESC",
  ASC: "ASC",
} as const

export const TRANSACTIONS_FILTERS_SORT_KEYS = {
  AMOUNT: "amount_cents",
  NAME: "name",
  DATE: "date",
} as const

export const TRANSACTIONS_SORT_OPTIONS = [
  {
    label: "Latest",
    id: `${TRANSACTIONS_FILTERS_SORT_KEYS.DATE}-${TRANSACTIONS_FILTERS_SORT_DIRECTIONS.DESC}`,
    config: {
      column: TRANSACTIONS_FILTERS_SORT_KEYS.DATE,
      direction: TRANSACTIONS_FILTERS_SORT_DIRECTIONS.DESC,
    },
  },
  {
    label: "Oldest",
    id: `${TRANSACTIONS_FILTERS_SORT_KEYS.DATE}-${TRANSACTIONS_FILTERS_SORT_DIRECTIONS.ASC}`,
    config: {
      column: TRANSACTIONS_FILTERS_SORT_KEYS.DATE,
      direction: TRANSACTIONS_FILTERS_SORT_DIRECTIONS.ASC,
    },
  },
  {
    label: "A to Z",
    id: `${TRANSACTIONS_FILTERS_SORT_KEYS.NAME}-${TRANSACTIONS_FILTERS_SORT_DIRECTIONS.DESC}`,
    config: {
      column: TRANSACTIONS_FILTERS_SORT_KEYS.NAME,
      direction: TRANSACTIONS_FILTERS_SORT_DIRECTIONS.DESC,
    },
  },
  {
    label: "Z to A",
    id: `${TRANSACTIONS_FILTERS_SORT_KEYS.NAME}-${TRANSACTIONS_FILTERS_SORT_DIRECTIONS.ASC}`,
    config: {
      column: TRANSACTIONS_FILTERS_SORT_KEYS.NAME,
      direction: TRANSACTIONS_FILTERS_SORT_DIRECTIONS.ASC,
    },
  },
  {
    label: "Highest",
    id: `${TRANSACTIONS_FILTERS_SORT_KEYS.AMOUNT}-${TRANSACTIONS_FILTERS_SORT_DIRECTIONS.DESC}`,
    config: {
      column: TRANSACTIONS_FILTERS_SORT_KEYS.AMOUNT,
      direction: TRANSACTIONS_FILTERS_SORT_DIRECTIONS.DESC,
    },
  },
  {
    label: "Lowest",
    id: `${TRANSACTIONS_FILTERS_SORT_KEYS.AMOUNT}-${TRANSACTIONS_FILTERS_SORT_DIRECTIONS.ASC}`,
    config: {
      column: TRANSACTIONS_FILTERS_SORT_KEYS.AMOUNT,
      direction: TRANSACTIONS_FILTERS_SORT_DIRECTIONS.ASC,
    },
  },
] as const

export const TRANSACTIONS_FILTERS_CATEGORIES_ALL_OPTION = {
  label: "All",
  value: "ALL",
  icon_name: null,
  color: null,
} as const
